CREATE TABLE Persons (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Phone NVARCHAR(20) NULL,
    Cpf NVARCHAR(14) NOT NULL UNIQUE,
    ZipCode NVARCHAR(10) NULL,
    Address NVARCHAR(255) NULL,
    Number NVARCHAR(10) NULL,
    Complement NVARCHAR(255) NULL,
    Neighborhood NVARCHAR(100) NULL,
    City NVARCHAR(100) NULL,
    State NVARCHAR(50) NULL,
    CreatedAt DATETIME DEFAULT GETDATE(),
    UpdatedAt DATETIME DEFAULT GETDATE(),
    Active BIT DEFAULT 1
);